"""Add user

Revision ID: 61d5529fb280
Revises: 4f5e25ada2b9
Create Date: 2023-10-14 21:05:55.035796

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '61d5529fb280'
down_revision: Union[str, None] = '4f5e25ada2b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contacts', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'contacts', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.add_column('users', sa.Column('username', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('password', sa.String(length=255), nullable=False))
    op.add_column('users', sa.Column('crated_at', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('avatar', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('refresh_token', sa.String(length=255), nullable=True))
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_index('ix_users_birthday', table_name='users')
    op.drop_index('ix_users_description', table_name='users')
    op.drop_index('ix_users_email', table_name='users')
    op.drop_index('ix_users_firstname', table_name='users')
    op.drop_index('ix_users_id', table_name='users')
    op.drop_index('ix_users_lastname', table_name='users')
    op.drop_index('ix_users_phone', table_name='users')
    op.create_unique_constraint(None, 'users', ['email'])
    op.drop_column('users', 'lastname')
    op.drop_column('users', 'birthday')
    op.drop_column('users', 'firstname')
    op.drop_column('users', 'phone')
    op.drop_column('users', 'description')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('phone', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('firstname', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('birthday', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('lastname', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'users', type_='unique')
    op.create_index('ix_users_phone', 'users', ['phone'], unique=False)
    op.create_index('ix_users_lastname', 'users', ['lastname'], unique=False)
    op.create_index('ix_users_id', 'users', ['id'], unique=False)
    op.create_index('ix_users_firstname', 'users', ['firstname'], unique=False)
    op.create_index('ix_users_email', 'users', ['email'], unique=False)
    op.create_index('ix_users_description', 'users', ['description'], unique=False)
    op.create_index('ix_users_birthday', 'users', ['birthday'], unique=False)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('users', 'refresh_token')
    op.drop_column('users', 'avatar')
    op.drop_column('users', 'crated_at')
    op.drop_column('users', 'password')
    op.drop_column('users', 'username')
    op.drop_constraint(None, 'contacts', type_='foreignkey')
    op.drop_column('contacts', 'user_id')
    # ### end Alembic commands ###
